on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'psalm.xml'
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'psalm.xml'

name: backwards compatibility

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@48ade4ccb74825ff7f725afc17591572ecbe71c5
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
