name: Update docs translation

on:
  pull_request:
    paths:
      - 'docs/po/**'
      - 'docs/pot/**'
      - 'docs/po4a.conf'
      - 'docs/po4a-base.conf'
      - 'docs/prepare-config.sh'
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.YIISOFT_GITHUB_TOKEN || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Prepare po4a configuration
        run: docs/prepare-config.sh

      - name: Use po4a
        uses: vjik/docker-run@v1
        with:
          image: ghcr.io/yiisoft-contrib/po4a:0.74
          volumes: ${{ github.workspace }}:/src
          workdir: /src/docs
          command: po4a po4a.conf && po4a po4a.conf

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docs translation
          file_pattern: 'docs'
