name: mutation test

on:
  pull_request:
    paths: &paths
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/mutation.yml'
      - 'composer.json'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

jobs:
  mutation:
    uses: yiisoft/actions/.github/workflows/infection.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.5']
      infection-args: "--ignore-msi-with-no-mutations"
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
