on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector.yml@48ade4ccb74825ff7f725afc17591572ecbe71c5
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
